import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/contexts/ModalContext";
import { Toaster } from "react-hot-toast";
import { QueryProvider } from "@/contexts/QueryProvider";
import { NextAuthProvider } from "@/contexts/NextAuthProvider";
import { SessionUserProvider } from "@/contexts/SessionUserContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <NextAuthProvider>
                    <QueryProvider>
                        <SessionUserProvider>
                            <ModalProvider>
                                {children}
                                <Toaster position="top-center" />
                            </ModalProvider>
                        </SessionUserProvider>
                    </QueryProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}
